In [9]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy

In [8]:
print("1. Import numpy as np and see the version")

import numpy as np
print(np.__version__)

1.18.2


In [11]:
print("2. How to create a 1D array?")
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print("3. How to create a boolean array?")
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
print("4. How to extract items that satisfy a given condition from 1D array?")
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [15]:
print("5. How to replace items that satisfy a condition with another value in numpy array?")
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [23]:

print("6. How to replace items that satisfy a condition without affecting the original array?")
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out


6. How to replace items that satisfy a condition without affecting the original array?
[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
print("7. How to reshape an array?"")
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
print("8. How to stack two arrays vertically?")
print("Solution 1:")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
print("8. How to stack two arrays vertically?")
print("Solution 2:")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
print("8. How to stack two arrays vertically?")
print("Solution 3:")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
print("9. How to stack two arrays horizontally?")
print("Solution 1:")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)

9. How to stack two arrays horizontally?
Solution 1:


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
print("9. How to stack two arrays horizontally?")
print("Solution 2:")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

9. How to stack two arrays horizontally?
Solution 2:


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [24]:
print("9. How to stack two arrays horizontally?")
print("Solution 3:")
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.c_[a,b]

9. How to stack two arrays horizontally?
Solution 3:


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [27]:
print("10. How to generate custom sequences in numpy without hardcoding?")
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

10. How to generate custom sequences in numpy without hardcoding?


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
print("11. How to get the common items between two python numpy arrays?")
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

11. How to get the common items between two python numpy arrays?


array([2, 4])

In [29]:
print("12. How to remove from one array those items that exist in another?")
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

12. How to remove from one array those items that exist in another?


array([1, 2, 3, 4])

In [30]:
print("13. How to get the positions where elements of two arrays match?")
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

13. How to get the positions where elements of two arrays match?


(array([1, 3, 5, 7], dtype=int64),)

In [31]:
print("14. How to extract all numbers between a given range from a numpy array?")
print("Solution 1:")
a = np.arange(15)

index = np.where((a >= 5) & (a <= 10))
a[index]

14. How to extract all numbers between a given range from a numpy array?
Solution 1:


array([ 5,  6,  7,  8,  9, 10])

In [32]:
print("14. How to extract all numbers between a given range from a numpy array?")
print("Solution 2:")
a = np.arange(15)

index = np.where(np.logical_and(a>=5, a<=10))
a[index]

14. How to extract all numbers between a given range from a numpy array?
Solution 2:


array([ 5,  6,  7,  8,  9, 10])

In [33]:
print("14. How to extract all numbers between a given range from a numpy array?")
print("Solution 3:")
a = np.arange(15)

a[(a >= 5) & (a <= 10)]

14. How to extract all numbers between a given range from a numpy array?
Solution 3:


array([ 5,  6,  7,  8,  9, 10])

In [34]:
print("15. How to make a python function that handles scalars to work on numpy arrays?")
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

15. How to make a python function that handles scalars to work on numpy arrays?


array([6., 7., 9., 8., 9., 7., 5.])

In [35]:
print("16. How to swap two columns in a 2d numpy array?")
arr = np.arange(9).reshape(3,3)
arr

arr[:, [1,0,2]]

16. How to swap two columns in a 2d numpy array?


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [36]:
print("17. How to swap two rows in a 2d numpy array?")
arr = np.arange(9).reshape(3,3)
arr

arr[[1,0,2], :]

17. How to swap two rows in a 2d numpy array?


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [37]:
print("18. How to reverse the rows of a 2D array?")
arr = np.arange(9).reshape(3,3)

arr[::-1]

18. How to reverse the rows of a 2D array?


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [39]:
print("19. How to reverse the columns of a 2D array?")
arr[:, ::-1]

19. How to reverse the columns of a 2D array?


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [41]:
print("20. How to create a 2D array containing random floats between 5 and 10?")
print("Solution 1:")
arr = np.arange(9).reshape(3,3)

rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

20. How to create a 2D array containing random floats between 5 and 10?
Solution 1:
[[7.72551663 9.74742934 8.05460797]
 [9.4780344  6.02892721 8.25853888]
 [6.89232317 5.10823409 9.36444648]
 [9.59264236 5.09120193 5.35586126]
 [8.69692874 9.21037024 7.6258805 ]]


In [42]:
print("20. How to create a 2D array containing random floats between 5 and 10?")
print("Solution 2:")
arr = np.arange(9).reshape(3,3)

rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

20. How to create a 2D array containing random floats between 5 and 10?
Solution 2:
[[5.00775369 9.37971453 6.73566032]
 [5.94554462 9.85631733 5.96098742]
 [6.4885598  6.71805657 5.47824281]
 [6.46044849 6.9804603  9.68539974]
 [9.90435829 8.5392266  9.61371954]]


In [43]:
print("21. How to print only 3 decimal places in python numpy array?")
rand_arr = np.random.random([5,3])

np.set_printoptions(precision=3)
rand_arr[:4]

21. How to print only 3 decimal places in python numpy array?


array([[0.076, 0.752, 0.012],
       [0.715, 0.228, 0.997],
       [0.019, 0.394, 0.808],
       [0.636, 0.353, 0.866]])

In [45]:
print("22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?")
# Reset printoptions (changed in previous snippet)
np.set_printoptions(suppress=False)

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?


array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [46]:
print("23. How to limit the number of items printed in output of numpy array?")
np.set_printoptions(threshold=6)
a = np.arange(15)
a

23. How to limit the number of items printed in output of numpy array?


array([ 0,  1,  2, ..., 12, 13, 14])

In [48]:
print("24. How to print the full numpy array without truncating?")
np.set_printoptions(threshold=6)
a = np.arange(15)

np.set_printoptions(threshold=sys.maxsize)
a

24. How to print the full numpy array without truncating?


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
print("25. How to import a dataset with numbers and texts keeping the text intact in python numpy?")
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]

25. How to import a dataset with numbers and texts keeping the text intact in python numpy?


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)